return @"Three young boys stared across the ravine and gazed upon a beautiful field of flowers. Though they each had the same view, they each saw different things. One saw an adventure, one saw a better future, and one saw an escape from the past. So together they descended into the valley. As they pressed forward the darkness began to envelope them. The shadows grew bolder, and the light became faint.

They soon came upon a split in the path. On the left nothing seemed to change, on the right a distant flicker lit the path.
The boy seeking adventure saw to the right an easy path, devoid of the excitement that the darkness promised. So he turned left.
The boy seeking a better future saw a trap, a torch meant to lure unsuspecting travelers to their doom. So he turned left. 
But the boy seeking an escape from the past saw an opportunity to leave the past behind. So the boys said their goodbyes and two went left and the other went right.

As the two boys pushed further through the darkness, they soon stumbled upon another split in the path they had trod. They had nearly completed their journey, and all that they had to do was climb to the top of the ravine to enter the field of flowers. To the left was a steep path covered in rocks. To the right was a twisting and winding path. The boy who sought a better future saw danger on the left. The boy who sought adventure saw only confusion and wasted time on the right. The two boys said goodbye and parted ways.

All three boys soon arrived at the top of the ravine and looked back at their journey. All were weary from their travels. The Boy seeking adventure found it, and would soon find more. The boy seeking a better future found one, better than he imagined. The boy seeking to flee his past did, and his present would soon erase the awful memory. The three boys shared the splendor of the flower field, and would soon meet many other travelers who crossed the ravine, each with their own stories, their own fears, and their own past. But all now shared the same story, they had arrived, and it was worth the trip.";
