// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // player
global.__objectDepths[1] = -89999999; // controller_object
global.__objectDepths[2] = -1410000000; // shader_controller
global.__objectDepths[3] = -1410065409; // mobile_buttons_controller
global.__objectDepths[4] = 0; // bullet_object
global.__objectDepths[5] = 0; // tomahawk_object
global.__objectDepths[6] = 0; // power_tomahawk_object
global.__objectDepths[7] = 0; // hurt_parent
global.__objectDepths[8] = 0; // hurt_block
global.__objectDepths[9] = 0; // hurt_block_player
global.__objectDepths[10] = 0; // allow_passage_block
global.__objectDepths[11] = 0; // building_parent
global.__objectDepths[12] = -9999999; // special_blocker
global.__objectDepths[13] = -9999999; // door_object
global.__objectDepths[14] = -9999999; // block_object
global.__objectDepths[15] = -9999999; // small_block_object
global.__objectDepths[16] = -9999999; // disappearing_block
global.__objectDepths[17] = -9999999; // stop_walk
global.__objectDepths[18] = 0; // snake_spawner
global.__objectDepths[19] = 0; // bear_spawner
global.__objectDepths[20] = 0; // buffalo_spawner
global.__objectDepths[21] = 0; // beaver_spawner
global.__objectDepths[22] = 0; // lizard_spawner
global.__objectDepths[23] = 0; // terrain_up_object
global.__objectDepths[24] = 0; // terrain_down_object
global.__objectDepths[25] = 0; // terrain_up_pathway_object
global.__objectDepths[26] = 0; // block_bullet_object
global.__objectDepths[27] = 0; // stuff_in_barrels
global.__objectDepths[28] = 0; // tumbleweed_maker
global.__objectDepths[29] = 0; // grass_holder
global.__objectDepths[30] = 0; // standaround_object
global.__objectDepths[31] = 0; // smithing_marker
global.__objectDepths[32] = 0; // cafe_object
global.__objectDepths[33] = 0; // blacksmith_back_object
global.__objectDepths[34] = 0; // blacksmith_front_object
global.__objectDepths[35] = 0; // barber_shop_object
global.__objectDepths[36] = 0; // general_store_object
global.__objectDepths[37] = 0; // news_building_object
global.__objectDepths[38] = 0; // warehouse_object
global.__objectDepths[39] = 0; // law_object
global.__objectDepths[40] = 0; // lumber_mill_building
global.__objectDepths[41] = 0; // lumber_object
global.__objectDepths[42] = 0; // lumber_mill_wheel_object
global.__objectDepths[43] = 0; // outpost_object
global.__objectDepths[44] = 0; // hotel_object
global.__objectDepths[45] = 0; // town_hall_object
global.__objectDepths[46] = 0; // library_building_object
global.__objectDepths[47] = 0; // church_object
global.__objectDepths[48] = 0; // house_object
global.__objectDepths[49] = 0; // teepee_object
global.__objectDepths[50] = 0; // pond_or_rose_house_object
global.__objectDepths[51] = 0; // pond_or_rose_sign_object
global.__objectDepths[52] = 0; // medicine_teepee_object
global.__objectDepths[53] = 0; // junk_building_1
global.__objectDepths[54] = 0; // junk_building_hotel
global.__objectDepths[55] = 0; // junk_building_store
global.__objectDepths[56] = 0; // junk_building_2
global.__objectDepths[57] = 0; // junk_building_3
global.__objectDepths[58] = 0; // junk_building_4
global.__objectDepths[59] = 0; // junk_building_5
global.__objectDepths[60] = 0; // junk_building_6
global.__objectDepths[61] = 0; // junk_building_9
global.__objectDepths[62] = 0; // junk_building_7
global.__objectDepths[63] = 0; // junk_building_8
global.__objectDepths[64] = 0; // or_house
global.__objectDepths[65] = 0; // or_town_hall
global.__objectDepths[66] = 0; // or_house_2
global.__objectDepths[67] = 0; // or_house_3
global.__objectDepths[68] = 0; // or_stand_object
global.__objectDepths[69] = 0; // or_hospital_sign_object
global.__objectDepths[70] = 0; // townsperson_controller
global.__objectDepths[71] = 0; // townsperson_object
global.__objectDepths[72] = 0; // chair_object_left
global.__objectDepths[73] = 0; // chair_object
global.__objectDepths[74] = 0; // chair_down_object
global.__objectDepths[75] = 0; // invs_chair_down
global.__objectDepths[76] = 0; // invs_chair_up
global.__objectDepths[77] = 0; // stump_object
global.__objectDepths[78] = 0; // couch_object
global.__objectDepths[79] = 0; // throne_object
global.__objectDepths[80] = 0; // park_bench_object
global.__objectDepths[81] = 0; // table_object
global.__objectDepths[82] = 0; // campfire_object
global.__objectDepths[83] = 0; // pulpit_object
global.__objectDepths[84] = 0; // bench_object
global.__objectDepths[85] = 0; // desk_object
global.__objectDepths[86] = 0; // bird_cage_object
global.__objectDepths[87] = 0; // stove_object
global.__objectDepths[88] = 0; // bed_object
global.__objectDepths[89] = 0; // bed_bedding_object
global.__objectDepths[90] = 0; // sleeping_bag_object
global.__objectDepths[91] = 0; // bed_person_sprite
global.__objectDepths[92] = 0; // dresser_object
global.__objectDepths[93] = 0; // library_shelf_object
global.__objectDepths[94] = 0; // mirror_object
global.__objectDepths[95] = 0; // shelf_object
global.__objectDepths[96] = 0; // jail_door_object
global.__objectDepths[97] = 0; // organ_object
global.__objectDepths[98] = 0; // curtain_object
global.__objectDepths[99] = 0; // anvil_object
global.__objectDepths[100] = 0; // chest_object
global.__objectDepths[101] = 0; // safe_object
global.__objectDepths[102] = 0; // sign_object
global.__objectDepths[103] = 0; // graveyard_sign
global.__objectDepths[104] = 0; // rock_object
global.__objectDepths[105] = 0; // totem_object
global.__objectDepths[106] = 0; // tree_object
global.__objectDepths[107] = 0; // new_tree_object
global.__objectDepths[108] = 0; // droop_tree_object
global.__objectDepths[109] = 0; // small_tree_object
global.__objectDepths[110] = 0; // cactus_object
global.__objectDepths[111] = 0; // dead_tree_object
global.__objectDepths[112] = 0; // fence_object
global.__objectDepths[113] = 0; // picket_fence_object
global.__objectDepths[114] = 0; // rope_fence_object
global.__objectDepths[115] = 0; // picket_fence_broken_object
global.__objectDepths[116] = 0; // fence_broken_object
global.__objectDepths[117] = 0; // torch_object
global.__objectDepths[118] = 0; // fancy_torch_object
global.__objectDepths[119] = 0; // tombstone_object
global.__objectDepths[120] = 0; // tombstone_fancy_object
global.__objectDepths[121] = 0; // graveyard_statue_object
global.__objectDepths[122] = 0; // tombstone_2_object
global.__objectDepths[123] = 0; // tombstone_decorative_object
global.__objectDepths[124] = 0; // tombstone_3_object
global.__objectDepths[125] = 0; // cross_object
global.__objectDepths[126] = 0; // sticks_tombstone_object
global.__objectDepths[127] = 100002; // water_object
global.__objectDepths[128] = 100002; // water_walk_object
global.__objectDepths[129] = 100001; // water_big_object
global.__objectDepths[130] = 999999; // lake_object
global.__objectDepths[131] = 999999; // final_background_object
global.__objectDepths[132] = 0; // water_fall_object
global.__objectDepths[133] = 0; // snow_tree
global.__objectDepths[134] = 0; // grass_bundle_object
global.__objectDepths[135] = 0; // desert_grass_bundle_object
global.__objectDepths[136] = 0; // palm_tree_object
global.__objectDepths[137] = 0; // weeds_bundle_object
global.__objectDepths[138] = 0; // desert_tree_object
global.__objectDepths[139] = 0; // agave_object
global.__objectDepths[140] = 0; // leafy_plant_object
global.__objectDepths[141] = 0; // shrub_object
global.__objectDepths[142] = 0; // reeds_object
global.__objectDepths[143] = 0; // xpo_sign
global.__objectDepths[144] = 99999; // terrain_rock
global.__objectDepths[145] = 0; // large_bridge_object
global.__objectDepths[146] = 0; // large_bridge_broken
global.__objectDepths[147] = 0; // small_bridge_object
global.__objectDepths[148] = 0; // desert_arch_object
global.__objectDepths[149] = 0; // pine_tree_no_snow
global.__objectDepths[150] = 0; // mine_tracks_object
global.__objectDepths[151] = 0; // mine_sign_object
global.__objectDepths[152] = 0; // crane_object
global.__objectDepths[153] = 0; // barrel_object
global.__objectDepths[154] = 0; // powder_keg_object
global.__objectDepths[155] = 0; // crate_object
global.__objectDepths[156] = 0; // dungeon_wall_object
global.__objectDepths[157] = 0; // dungeon_wall_bright_object
global.__objectDepths[158] = 0; // tumbleweed_object
global.__objectDepths[159] = 0; // snake_object
global.__objectDepths[160] = 0; // wolf_object
global.__objectDepths[161] = 0; // bear_object
global.__objectDepths[162] = 0; // lizard_object
global.__objectDepths[163] = 0; // buffalo_object
global.__objectDepths[164] = 0; // beaver_object
global.__objectDepths[165] = 0; // crab_object
global.__objectDepths[166] = 0; // disappear_object
global.__objectDepths[167] = -10604; // swirl_effect_object
global.__objectDepths[168] = 0; // expel_object
global.__objectDepths[169] = 0; // explosion_object
global.__objectDepths[170] = 0; // bridge_object
global.__objectDepths[171] = 0; // bridge_switch_object
global.__objectDepths[172] = 0; // cowboy_character_object
global.__objectDepths[173] = 0; // indian_character_object
global.__objectDepths[174] = 0; // girl_character_object
global.__objectDepths[175] = 0; // or_character_object
global.__objectDepths[176] = 0; // custom_arrow_object
global.__objectDepths[177] = -99000; // custom_character_controller
global.__objectDepths[178] = -9999; // delivery_bird_object
global.__objectDepths[179] = -9998; // note_object
global.__objectDepths[180] = 0; // title_cactus
global.__objectDepths[181] = 0; // story_controller
global.__objectDepths[182] = -99; // select_character_object
global.__objectDepths[183] = 1; // controls_controller
global.__objectDepths[184] = -1410065407; // game_over_controller
global.__objectDepths[185] = 0; // story_ground_scroll_object
global.__objectDepths[186] = -3; // title_player
global.__objectDepths[187] = 0; // game_load_controller
global.__objectDepths[188] = 0; // book_parent
global.__objectDepths[189] = 0; // beaver_pelt_object
global.__objectDepths[190] = 0; // buffalo_skin_object
global.__objectDepths[191] = 0; // bear_skin_object
global.__objectDepths[192] = 0; // lizard_scale_object
global.__objectDepths[193] = 0; // snake_skin_object
global.__objectDepths[194] = 0; // crab_shell_object
global.__objectDepths[195] = 0; // book_object
global.__objectDepths[196] = 0; // ladder_object
global.__objectDepths[197] = 0; // actionly_door_h
global.__objectDepths[198] = 0; // actionly_door_wide
global.__objectDepths[199] = 0; // actionly_object_parent
global.__objectDepths[200] = 0; // actionly_block_parent
global.__objectDepths[201] = 0; // actionly_pressure_plate
global.__objectDepths[202] = 0; // actionly_switch
global.__objectDepths[203] = 0; // actionly_invisible_switch
global.__objectDepths[204] = 0; // actionly_target
global.__objectDepths[205] = 0; // actionly_spinner
global.__objectDepths[206] = 0; // color_changer
global.__objectDepths[207] = -90; // press_start_object
global.__objectDepths[208] = 0; // menu_button_object
global.__objectDepths[209] = -90000; // inventory_menu_controller
global.__objectDepths[210] = -90000; // events_menu_controller
global.__objectDepths[211] = -90000; // settings_menu_controller
global.__objectDepths[212] = 0; // crafting_menu_controller
global.__objectDepths[213] = 0; // gear_menu_controller


global.__objectNames[0] = "player";
global.__objectNames[1] = "controller_object";
global.__objectNames[2] = "shader_controller";
global.__objectNames[3] = "mobile_buttons_controller";
global.__objectNames[4] = "bullet_object";
global.__objectNames[5] = "tomahawk_object";
global.__objectNames[6] = "power_tomahawk_object";
global.__objectNames[7] = "hurt_parent";
global.__objectNames[8] = "hurt_block";
global.__objectNames[9] = "hurt_block_player";
global.__objectNames[10] = "allow_passage_block";
global.__objectNames[11] = "building_parent";
global.__objectNames[12] = "special_blocker";
global.__objectNames[13] = "door_object";
global.__objectNames[14] = "block_object";
global.__objectNames[15] = "small_block_object";
global.__objectNames[16] = "disappearing_block";
global.__objectNames[17] = "stop_walk";
global.__objectNames[18] = "snake_spawner";
global.__objectNames[19] = "bear_spawner";
global.__objectNames[20] = "buffalo_spawner";
global.__objectNames[21] = "beaver_spawner";
global.__objectNames[22] = "lizard_spawner";
global.__objectNames[23] = "terrain_up_object";
global.__objectNames[24] = "terrain_down_object";
global.__objectNames[25] = "terrain_up_pathway_object";
global.__objectNames[26] = "block_bullet_object";
global.__objectNames[27] = "stuff_in_barrels";
global.__objectNames[28] = "tumbleweed_maker";
global.__objectNames[29] = "grass_holder";
global.__objectNames[30] = "standaround_object";
global.__objectNames[31] = "smithing_marker";
global.__objectNames[32] = "cafe_object";
global.__objectNames[33] = "blacksmith_back_object";
global.__objectNames[34] = "blacksmith_front_object";
global.__objectNames[35] = "barber_shop_object";
global.__objectNames[36] = "general_store_object";
global.__objectNames[37] = "news_building_object";
global.__objectNames[38] = "warehouse_object";
global.__objectNames[39] = "law_object";
global.__objectNames[40] = "lumber_mill_building";
global.__objectNames[41] = "lumber_object";
global.__objectNames[42] = "lumber_mill_wheel_object";
global.__objectNames[43] = "outpost_object";
global.__objectNames[44] = "hotel_object";
global.__objectNames[45] = "town_hall_object";
global.__objectNames[46] = "library_building_object";
global.__objectNames[47] = "church_object";
global.__objectNames[48] = "house_object";
global.__objectNames[49] = "teepee_object";
global.__objectNames[50] = "pond_or_rose_house_object";
global.__objectNames[51] = "pond_or_rose_sign_object";
global.__objectNames[52] = "medicine_teepee_object";
global.__objectNames[53] = "junk_building_1";
global.__objectNames[54] = "junk_building_hotel";
global.__objectNames[55] = "junk_building_store";
global.__objectNames[56] = "junk_building_2";
global.__objectNames[57] = "junk_building_3";
global.__objectNames[58] = "junk_building_4";
global.__objectNames[59] = "junk_building_5";
global.__objectNames[60] = "junk_building_6";
global.__objectNames[61] = "junk_building_9";
global.__objectNames[62] = "junk_building_7";
global.__objectNames[63] = "junk_building_8";
global.__objectNames[64] = "or_house";
global.__objectNames[65] = "or_town_hall";
global.__objectNames[66] = "or_house_2";
global.__objectNames[67] = "or_house_3";
global.__objectNames[68] = "or_stand_object";
global.__objectNames[69] = "or_hospital_sign_object";
global.__objectNames[70] = "townsperson_controller";
global.__objectNames[71] = "townsperson_object";
global.__objectNames[72] = "chair_object_left";
global.__objectNames[73] = "chair_object";
global.__objectNames[74] = "chair_down_object";
global.__objectNames[75] = "invs_chair_down";
global.__objectNames[76] = "invs_chair_up";
global.__objectNames[77] = "stump_object";
global.__objectNames[78] = "couch_object";
global.__objectNames[79] = "throne_object";
global.__objectNames[80] = "park_bench_object";
global.__objectNames[81] = "table_object";
global.__objectNames[82] = "campfire_object";
global.__objectNames[83] = "pulpit_object";
global.__objectNames[84] = "bench_object";
global.__objectNames[85] = "desk_object";
global.__objectNames[86] = "bird_cage_object";
global.__objectNames[87] = "stove_object";
global.__objectNames[88] = "bed_object";
global.__objectNames[89] = "bed_bedding_object";
global.__objectNames[90] = "sleeping_bag_object";
global.__objectNames[91] = "bed_person_sprite";
global.__objectNames[92] = "dresser_object";
global.__objectNames[93] = "library_shelf_object";
global.__objectNames[94] = "mirror_object";
global.__objectNames[95] = "shelf_object";
global.__objectNames[96] = "jail_door_object";
global.__objectNames[97] = "organ_object";
global.__objectNames[98] = "curtain_object";
global.__objectNames[99] = "anvil_object";
global.__objectNames[100] = "chest_object";
global.__objectNames[101] = "safe_object";
global.__objectNames[102] = "sign_object";
global.__objectNames[103] = "graveyard_sign";
global.__objectNames[104] = "rock_object";
global.__objectNames[105] = "totem_object";
global.__objectNames[106] = "tree_object";
global.__objectNames[107] = "new_tree_object";
global.__objectNames[108] = "droop_tree_object";
global.__objectNames[109] = "small_tree_object";
global.__objectNames[110] = "cactus_object";
global.__objectNames[111] = "dead_tree_object";
global.__objectNames[112] = "fence_object";
global.__objectNames[113] = "picket_fence_object";
global.__objectNames[114] = "rope_fence_object";
global.__objectNames[115] = "picket_fence_broken_object";
global.__objectNames[116] = "fence_broken_object";
global.__objectNames[117] = "torch_object";
global.__objectNames[118] = "fancy_torch_object";
global.__objectNames[119] = "tombstone_object";
global.__objectNames[120] = "tombstone_fancy_object";
global.__objectNames[121] = "graveyard_statue_object";
global.__objectNames[122] = "tombstone_2_object";
global.__objectNames[123] = "tombstone_decorative_object";
global.__objectNames[124] = "tombstone_3_object";
global.__objectNames[125] = "cross_object";
global.__objectNames[126] = "sticks_tombstone_object";
global.__objectNames[127] = "water_object";
global.__objectNames[128] = "water_walk_object";
global.__objectNames[129] = "water_big_object";
global.__objectNames[130] = "lake_object";
global.__objectNames[131] = "final_background_object";
global.__objectNames[132] = "water_fall_object";
global.__objectNames[133] = "snow_tree";
global.__objectNames[134] = "grass_bundle_object";
global.__objectNames[135] = "desert_grass_bundle_object";
global.__objectNames[136] = "palm_tree_object";
global.__objectNames[137] = "weeds_bundle_object";
global.__objectNames[138] = "desert_tree_object";
global.__objectNames[139] = "agave_object";
global.__objectNames[140] = "leafy_plant_object";
global.__objectNames[141] = "shrub_object";
global.__objectNames[142] = "reeds_object";
global.__objectNames[143] = "xpo_sign";
global.__objectNames[144] = "terrain_rock";
global.__objectNames[145] = "large_bridge_object";
global.__objectNames[146] = "large_bridge_broken";
global.__objectNames[147] = "small_bridge_object";
global.__objectNames[148] = "desert_arch_object";
global.__objectNames[149] = "pine_tree_no_snow";
global.__objectNames[150] = "mine_tracks_object";
global.__objectNames[151] = "mine_sign_object";
global.__objectNames[152] = "crane_object";
global.__objectNames[153] = "barrel_object";
global.__objectNames[154] = "powder_keg_object";
global.__objectNames[155] = "crate_object";
global.__objectNames[156] = "dungeon_wall_object";
global.__objectNames[157] = "dungeon_wall_bright_object";
global.__objectNames[158] = "tumbleweed_object";
global.__objectNames[159] = "snake_object";
global.__objectNames[160] = "wolf_object";
global.__objectNames[161] = "bear_object";
global.__objectNames[162] = "lizard_object";
global.__objectNames[163] = "buffalo_object";
global.__objectNames[164] = "beaver_object";
global.__objectNames[165] = "crab_object";
global.__objectNames[166] = "disappear_object";
global.__objectNames[167] = "swirl_effect_object";
global.__objectNames[168] = "expel_object";
global.__objectNames[169] = "explosion_object";
global.__objectNames[170] = "bridge_object";
global.__objectNames[171] = "bridge_switch_object";
global.__objectNames[172] = "cowboy_character_object";
global.__objectNames[173] = "indian_character_object";
global.__objectNames[174] = "girl_character_object";
global.__objectNames[175] = "or_character_object";
global.__objectNames[176] = "custom_arrow_object";
global.__objectNames[177] = "custom_character_controller";
global.__objectNames[178] = "delivery_bird_object";
global.__objectNames[179] = "note_object";
global.__objectNames[180] = "title_cactus";
global.__objectNames[181] = "story_controller";
global.__objectNames[182] = "select_character_object";
global.__objectNames[183] = "controls_controller";
global.__objectNames[184] = "game_over_controller";
global.__objectNames[185] = "story_ground_scroll_object";
global.__objectNames[186] = "title_player";
global.__objectNames[187] = "game_load_controller";
global.__objectNames[188] = "book_parent";
global.__objectNames[189] = "beaver_pelt_object";
global.__objectNames[190] = "buffalo_skin_object";
global.__objectNames[191] = "bear_skin_object";
global.__objectNames[192] = "lizard_scale_object";
global.__objectNames[193] = "snake_skin_object";
global.__objectNames[194] = "crab_shell_object";
global.__objectNames[195] = "book_object";
global.__objectNames[196] = "ladder_object";
global.__objectNames[197] = "actionly_door_h";
global.__objectNames[198] = "actionly_door_wide";
global.__objectNames[199] = "actionly_object_parent";
global.__objectNames[200] = "actionly_block_parent";
global.__objectNames[201] = "actionly_pressure_plate";
global.__objectNames[202] = "actionly_switch";
global.__objectNames[203] = "actionly_invisible_switch";
global.__objectNames[204] = "actionly_target";
global.__objectNames[205] = "actionly_spinner";
global.__objectNames[206] = "color_changer";
global.__objectNames[207] = "press_start_object";
global.__objectNames[208] = "menu_button_object";
global.__objectNames[209] = "inventory_menu_controller";
global.__objectNames[210] = "events_menu_controller";
global.__objectNames[211] = "settings_menu_controller";
global.__objectNames[212] = "crafting_menu_controller";
global.__objectNames[213] = "gear_menu_controller";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for