/// @description init_actionly_receiver(remote,toggle?,delay,speed,sound)
/// @param remote
/// @param toggle?
/// @param delay
/// @param speed
/// @param sound
image_speed = 0;
remote = argument0;
toggle = argument1;
delay = argument2;
animation_speed = argument3;
activated = false;
past_value = false;
depth = -y;
timer = 0;
my_sound = argument4;
